title: Benjamin Kabbis

# Specify the path to the logo. Ensure that the file "MyImage.jpg" exists in the correct directory (e.g., the root folder or an "assets" folder).
logo: Mypic.jpg

# A brief description of your website or personal brand
description: > 
  I am a Data Analyst with 2+ years of experience turning complex data into actionable insights. Skilled in Python, SQL, Excel, Power BI, and Tableau, I find passion in data visualization, predictive modeling,and process optimization. I have successfully executed data migration, improved decision-making velocity, and minimized operating costs. Data security and compliance are at the heart of what I do, along with business acumen and stakeholder management & Agile experience to deliver real solutions.
 

#show_downloads: true

#google_analytics:

theme: jekyll-theme-minimal
