title: Benjamin Kabbis

# Specify the path to the logo. Ensure that the file "MyImage.jpg" exists in the correct directory (e.g., the root folder or an "assets" folder).
logo: Mypic.jpg

# A brief description of your website or personal brand
description: > 
  I am a Data Analyst
  
  Location: United Kingdom

#show_downloads: true

#google_analytics:

theme: jekyll-theme-minimal
